AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

Resources:

  RaddTransactionDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-radd-transaction'
      AttributeDefinitions:
        - AttributeName: "operationId"
          AttributeType: "S"
        - AttributeName: "operationType"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "recipientId"
          AttributeType: "S"
        - AttributeName: "delegateId"
          AttributeType: "S"
        - AttributeName: "qrCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "operationId"
          KeyType: "HASH"
        - AttributeName: "operationType"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "iun-transaction-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "recipient-transaction-index"
          KeySchema:
            - AttributeName: "recipientId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "delegate-transaction-index"
          KeySchema:
            - AttributeName: "delegateId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: "qrcode-transaction-index"
          KeySchema:
            - AttributeName: "qrCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  OperationsAndIunsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-operations-iuns'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "operationId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "iun-and-operation-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
            - AttributeName: "operationId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
        
  RaddLogGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-radd-fsu'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
Outputs:
  RaddTransactionDynamoTableName:
    Description: Name of dynamodb table containing radd transaction
    Value: !Ref RaddTransactionDynamoTable

  OperationsAndIunsDynamoTableName:
    Description: Name of dynamodb table containing iuns and operations
    Value: !Ref OperationsAndIunsDynamoTable

  RaddTransactionDynamoTableArn:
    Description: ARN of dynamodb table containing transaction
    Value: !Sub '${RaddTransactionDynamoTable.Arn}'

  OperationsAndIunsDynamoTableArn:
    Description: ARN of dynamodb table containing iuns and operations
    Value: !Sub '${OperationsAndIunsDynamoTable.Arn}'

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt RaddLogGroup.Outputs.LogGroupName